[package]
name = "rust-random-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
once_cell = "1.18.0"
sha256 = "1.3.0"
